HOST: https://api.loader.io/v2

--- loader.io API load testing documentation ---

---
All requests require an API key. While you can specify the API key in the body of your request, we’d prefer it be passed via the loaderio-Auth header. You can do this as follows:

In the Header: loaderio-Auth: {api_key}

In the Body: api_key={api_key} 
---

--
Application Resources
--

List registered applications
GET /apps
> loaderio-Auth: {api_key}
> Content-Type: application/json
< 200
< Content-Type: application/json
[
  {
    "app": "gonnacrushya.com",
    "status": "verified",
    "app_id": "0f2fabf74c5451cf71dce7cf43987477"
  },
  {
    "app": "google.com",
    "status": "unverified",
    "app_id": "b579bbed7ef480e7318ac4d7b69e5caa"
  }
]

Application status
GET /apps/{app_id}
> loaderio-Auth: {api_key}
> Content-Type: application/json
< 200
< Content-Type: application/json
{
  "app": "gonnacrushya.com",
  "status": "verified",
  "app_id": "0f2fabf74c5451cf71dce7cf43987477"
}

Register a new application

Format: myapp.com or www.myapp.com (note: myapp.com & www.myapp.com are different applications)
POST /apps
> loaderio-Auth: {api_key}
> Content-Type: application/json
{
    "app": "gonnacrushya.com"
}
< 200
< Content-Type: application/json
{
  "message": "success",
  "app_id": "0f2fabf74c5451cf71dce7cf43987477",
  "verification_id": "loaderio-0f2fabf74c5451cf71dce7cf43987477"
}

Verify a registered application
POST /apps/{app_id}/verify
> loaderio-Auth: {api_key}
> Content-Type: application/json
< 200
< Content-Type: application/json
{
  "app_id": "0f2fabf74c5451cf71dce7cf43987477",
  "message": "success"
}

--
Test Resources
--

List of load tests
GET /tests
> loaderio-Auth: {api_key}
> Content-Type: application/json
< 200
< Content-Type: application/json
[
  {
    "name": "GonnaCrushYa",
    "duration": 60,
    "timeout": 0,
    "notes": null,
    "from": 0,
    "to": 250,
    "status": "complete",
    "test_id": "0642ee5387b4ee35b581b6bf1332c70b",
    "request_type": "GET",
    "url": "http://gonnacrushya.com"
  }
]

Create a new load test
POST /tests
> loaderio-Auth: {api_key}
> Content-type: application/json
{
  "load": "0-250-60", 
  "callback_url": "http://gonnacrushya.com/loader-callback",
  "name": "GonnaCrushYa Home Page",
  "timeout": 10000,
  "email_callback": "crusher@loader.io",
  "test_type": "cycling",
  "notes": "Going to kicks the crap out of this server",
  "user_login": "login",
  "user_password": "password",
  "scheduled_at": "2013-5-15 3:30:00",
  "urls": [
    {
      "url": "http://gonnacrushya.com", 
      "request_type": "GET",
      "post_body": "post body params go here",
	  "payload_file_url": "http://loader.io/payload_file.yml",
	  "headers": { "header1": "value1", "header2": "value2" },
	  "request_params": { "params1": "value1", "params2": "value2" }
	}
  ]
}
< 200
< Content-Type: application/json
{
    "message":"success",
    "test_id":"0642ee5387b4ee35b581b6bf1332c70b"
}

Load test status
GET /tests/{test_id}
> loaderio-Auth: {api_key}
> Content-type: application/json
< 200
< Content-type: application/json
{
  "name": "GonnaCrushYa Home Page",
  "duration": 60,
  "timeout": 10000,
  "notes": "",
  "from": 0,
  "to": 250,
  "status": "complete",
  "test_id": "0642ee5387b4ee35b581b6bf1332c70b",
  "request_type": "GET",
  "url": "http://gonnacrushya.com.com"
}

Load test results
GET /tests/{test_id}/results
> loaderio-Auth: {api_key}
> Content-type: application/json
< 200
< Content-type: application/json
{
  "name": "GonnaCrushYa Home Page",
  "duration": 60,
  "timeout": 10000,
  "notes": "",
  "from": 0,
  "to": 250,
  "status": "complete",
  "test_id": "0642ee5387b4ee35b581b6bf1332c70b",
  "request_type": "GET",
  "url": "http://gonnacrushya.com",
  "results_data": {
    "started_at": "2013-05-09T23:31:25+03:00",
    "public_results_url": "http://loader.io/results/0642ee5387b4ee35b581b6bf1332c70b",
    "avg_response_time": 7,
    "avg_error_rate": 0.0,
    "success": 213154,
    "error": 0,
    "timeout_error": 0,
    "network_error": 0, 
    "data_sent": 470857186,
    "data_received": 23666310
  }
}

Stop load test
PUT /tests/{test_id}/stop
> loaderio-Auth: {api_key}
> Content-type: application/json
< 200
< Content-type: application/json
{
  "name": "GonnaCrushYa Home Page",
  "duration": 60,
  "timeout": 10000,
  "notes": "",
  "from": 0,
  "to": 250,
  "status": "complete",
  "test_id": "0642ee5387b4ee35b581b6bf1332c70b",
  "request_type": "GET",
  "url": "http://gonnacrushya.com"
}

--
Servers
--

Load test server's ip addresses
GET /servers
> loaderio-Auth: {api_key}
> Content-type: application/json
< 200
< Content-type: application/json
{
  "ip_addresses": ["127.0.0.1"]
}