HOST: https://api.loader.io/v2

--- loader.io API load testing documentation ---

---
All requests require an API key. While you can specify the API key in the body of your request, we’d prefer it be passed via the loaderio-Auth header. You can do this as follows:

In the Header: loaderio-Auth: {api_key}

In the Body: api_key={api_key} 
---

--
Application Resources
--

List registered applications
GET /apps
> loaderio-Auth: {api_key}
> Content-Type: application/json
< 200
< Content-Type: application/json
[
  {
    "app": "gonnacrushya.com",
    "status": "verified",
    "app_id": "0f2fabf74c5451cf71dce7cf43987477"
  },
  {
    "app": "google.com",
    "status": "unverified",
    "app_id": "b579bbed7ef480e7318ac4d7b69e5caa"
  }
]

Application status
GET /apps/{app_id}
> loaderio-Auth: {api_key}
> Content-Type: application/json
< 200
< Content-Type: application/json
{
  "app": "gonnacrushya.com",
  "status": "verified",
  "app_id": "0f2fabf74c5451cf71dce7cf43987477"
}
+++++
< 404
< Content-Type: application/json
{
  "message":"error",
  "errors":["Requested record was not found"]
}

Register a new application

Format: myapp.com or www.myapp.com (note: myapp.com & www.myapp.com are different applications)
POST /apps
> loaderio-Auth: {api_key}
> Content-Type: application/json
{
    "app": "gonnacrushya.com"
}
< 200
< Content-Type: application/json
{
  "message": "success",
  "app_id": "0f2fabf74c5451cf71dce7cf43987477",
  "verification_id": "loaderio-0f2fabf74c5451cf71dce7cf43987477"
}
+++++
< 422
< Content-Type: application/json
{
  "message":"error",
  "errors":["We are unable to register this app"]
}

Verify a registered application
POST /apps/{app_id}/verify
> loaderio-Auth: {api_key}
> Content-Type: application/json
< 200
< Content-Type: application/json
{
  "app_id": "0f2fabf74c5451cf71dce7cf43987477",
  "message": "success"
}
+++++
< 422
< Content-Type: application/json
{
  "app_id": "0f2fabf74c5451cf71dce7cf43987477",
  "message":"error",
  "errors":["can't verify domain gonnacrushya.com"]
}
+++++
< 404
< Content-Type: application/json
{
  "message":"error",
  "errors":["Requested record was not found"]
}

--
Test Resources
--

List of load tests
GET /tests
> loaderio-Auth: {api_key}
> Content-Type: application/json
< 200
< Content-Type: application/json
[
  {
    "name":"",
    "duration":60,
    "timeout":10000,
    "notes":"",
    "from":0,
    "to":60,
    "status":"complete",
    "test_id":"9b24d675afb6c09c6813a79c956f0d02",
    "test_type":"Non-Cycling",
    "callback":"http://loader.io",
    "callback_email":"test@mail.com",
    "scheduled_at": "2013-06-07T19:30:00+03:00",
    "urls":
    [
      {
        "url":"http://loader.io/signin",
        "raw_post_body":null,
        "request_type":"GET",
        "payload_file_url":null,
        "headers":{ "header": "value", "header2": "value2" },
        "request_params":{ "param": "value", "param2": "value2" },
        "authentication":{"login": "login", "password": "password", "type": "basic"}
      }
    ]
  }
]

List of active load tests (verified, not archived)
GET /tests/active
> loaderio-Auth: {api_key}
> Content-Type: application/json
< 200
< Content-Type: application/json
[
  {
    "name":"",
    "duration":60,
    "timeout":10000,
    "notes":"",
    "from":0,
    "to":60,
    "status":"complete",
    "test_id":"9b24d675afb6c09c6813a79c956f0d02",
    "test_type":"Non-Cycling",
    "callback":"http://loader.io",
    "callback_email":"test@mail.com",
    "scheduled_at": "2013-06-07T19:30:00+03:00",
    "urls":
    [
      {
        "url":"http://loader.io/signin",
        "raw_post_body":null,
        "request_type":"GET",
        "payload_file_url":null,
        "headers":{ "header": "value", "header2": "value2" },
        "request_params":{ "param": "value", "param2": "value2" },
        "authentication":{"login": "login", "password": "password", "type": "basic"}
      }
    ]
  }
]

Create a new load test
POST /tests
> loaderio-Auth: {api_key}
> Content-type: application/json
{
  "initial": 0,
  "total": 60,
  "duration": 60,
  "callback": "http://gonnacrushya.com/loader-callback",
  "name": "GonnaCrushYa Home Page",
  "timeout": 10000,
  "callback_email": "crusher@loader.io",
  "test_type": "cycling",
  "notes": "Going to kicks the crap out of this server",
  "scheduled_at": "2013-5-15 3:30:00",
  "urls": [
    {
      "url": "http://gonnacrushya.com", 
      "request_type": "GET",
      "post_body": "post body params go here",
      "payload_file_url": "http://loader.io/payload_file.yml",
      "authentication": {"login": "login", "password": "secret", "type": "basic"},
	    "headers": { "header1": "value1", "header2": "value2" },
	    "request_params": { "params1": "value1", "params2": "value2" }
	}
  ]
}
< 200
< Content-Type: application/json
{
    "message":"success",
    "test_id":"0642ee5387b4ee35b581b6bf1332c70b",
    "status":"processing"
    "summary_id": "35b581b6bf1332c70b0642ee5387b4ee"
}
+++++
< 200
< Content-Type: application/json
{
    "message":"success",
    "test_id":"0642ee5387b4ee35b581b6bf1332c70b",
    "status":"unverified"
}
+++++
< 422
< Content-Type: application/json
{
    "message":"error",
    "errors":["can't create test"]
}

Load test status
GET /tests/{test_id}
> loaderio-Auth: {api_key}
> Content-type: application/json
< 200
< Content-type: application/json
{
  "name":"",
  "duration":60,
  "timeout":10000,
  "notes":"",
  "from":0,
  "to":60,
  "status":"complete",
  "test_id":"9b24d675afb6c09c6813a79c956f0d02",
  "test_type":"Non-Cycling",
  "callback":"http://loader.io",
  "callback_email":"test@mail.com",
  "scheduled_at": "2013-06-07T19:30:00+03:00",
  "urls":
  [
    {
      "url":"http://loader.io/signin",
      "raw_post_body":null,
      "request_type":"GET",
      "payload_file_url":null,
      "headers":{ "header": "value", "header2": "value2" },
      "request_params":{"param": "value", "param2": "value2" },
      "authentication":{"login": "login", "password": "password", "type": "basic"}
    }
  ]
}
+++++
< 404
< Content-Type: application/json
{
  "message":"error",
  "errors":["Requested record was not found"]
}

Run load test
PUT /tests/{test_id}/run
> loaderio-Auth: {api_key}
> Content-type: application/json
< 200
< Content-Type: application/json
{
    "message":"success",
    "test_id":"0642ee5387b4ee35b581b6bf1332c70b",
    "status":"processing"
    "summary_id": "35b581b6bf1332c70b0642ee5387b4ee"
}
+++++
< 404
< Content-Type: application/json
{
  "message":"error",
  "errors":["Requested record was not found"]
}
+++++
< 422
< Content-Type: application/json
{
    "message":"error",
    "errors":["Can't run test for unverified application"]
}


Stop load test
PUT /tests/{test_id}/stop
> loaderio-Auth: {api_key}
> Content-type: application/json
< 200
< Content-type: application/json
{
  "message":"success",
  "test_id":"1187538bb5d5fd60a1b99a6e67978c15",
  "status":"finished",
  "summary_id":"7c55ad8408f7c4326b7fa0e069b7a011"
}
+++++
< 404
< Content-Type: application/json
{
  "message":"error",
  "errors":["Requested record was not found"]
}
+++++
< 422
< Content-Type: application/json
{
    "message":"error",
    "errors":["Can't stop test with finished status"]
}


--
Test results
--

Load test results
GET /tests/{test_id}/summaries
> loaderio-Auth: {api_key}
> Content-type: application/json
< 200
< Content-type: application/json
[
  {
    "summary_id": "8fb213af34c1cf7b675dc21e900e533a",
    "started_at":"2013-06-10T23:42:01+02:00",
    "status":"ready",
    "public_results_url":"http://loader.io/results/a72944b62d576f0f68fb30ca41d20b99/summaries/8fb213af34c1cf7b675dc21e900e533a",
    "success":77,
    "error":0,
    "timeout_error":0,
    "network_error":0,
    "data_sent":28259,
    "data_received":8393,
    "avg_response_time":1,
    "avg_error_rate":0.0
  }
]
+++++
< 404
< Content-Type: application/json
{
  "message":"error",
  "errors":["Requested record was not found"]
}

Load test result
GET /tests/{test_id}/summaries/{summary_id}
> loaderio-Auth: {api_key}
> Content-type: application/json
< 200
< Content-type: application/json
{
  "summary_id": "8fb213af34c1cf7b675dc21e900e533a",
  "started_at":"2013-06-10T23:42:01+02:00",
  "status":"ready",
  "public_results_url":"http://loader.io/results/a72944b62d576f0f68fb30ca41d20b99/summaries/8fb213af34c1cf7b675dc21e900e533a",
  "success":77,
  "error":0,
  "timeout_error":0,
  "network_error":0,
  "data_sent":28259,
  "data_received":8393,
  "avg_response_time":1,
  "avg_error_rate":0.0
}
+++++
< 404
< Content-Type: application/json
{
  "message":"error",
  "errors":["Requested record was not found"]
}

--
Servers
--

Load test server's ip addresses
GET /servers
> loaderio-Auth: {api_key}
> Content-type: application/json
< 200
< Content-type: application/json
{
  "ip_addresses": ["127.0.0.1"]
}